language: php

env:
  global:
    - SYMFONY__db_host=localhost
    - SYMFONY__db_port=3306
    - SYMFONY__db_user=root
    - SYMFONY__db_password=""

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer install --dev
  - mysql -e 'CREATE DATABASE modera_languages_bundle'